### ISSUE TITLE
 CNN/daily mail dataset

### ISSUE THREAD

**Issue by MousaMohammed** [yahah100/text_summarization#1]
Hi,
May I know if there is any way to get the CNN/daily mail dataset from TensorFlow directly but for an extractive task not for abstractive

**Comment by yahah100** [comment]
I'm not sure if I understand your question right. But it sounds like the task, extractive or abstractive, depends on your model not on the dataset.

**Comment by yahah100** [comment]
Or you have to look into another dataset from [https://www.tensorflow.org/datasets/catalog/]
